### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by smalluk** [CiscoSecurity/tr-04-get-dispositions#3]
After updating the credentials and changing the URL to EU since I am in the EU region i get the following error:

Enter an observable: c056b6ff08695b6ff0e4aa58afaff14a7d4c343cdb35517625fb03efd4b11f31
Auth failed, generating new token.
Traceback (most recent call last):
  File "get_dispositions.py", line 129, in <module>
    main()
  File "get_dispositions.py", line 115, in main
    for module in response_json['data']:
KeyError: 'data'

**Comment by smalluk** [comment]
Looks like the API credentials that were generated did not have the correct permissions. I created a new key and gave it the permissions:
Enrich: Read
Event: Read
Global Intel: Read
Inspect: Read
Oauth

Unsure if all 5 are required for this script but it is now working. Could you list the minimum permissions required please?
